
import React from 'react';
import { Bot, Sparkles, MessageCircle, FileJson, Telescope, BrainCircuit, Lightbulb, Workflow, Feather, Megaphone, Target, BarChart3, ReceiptText, Code, Database, Rocket, LayoutDashboard, Settings, CircleDashed } from 'lucide-react';

const AiIcon = ({ icon }: { icon: React.ReactNode }) => (
  <span className="relative inline-flex items-center justify-center">
    {icon}
    <Sparkles className="absolute -top-1 -right-1 h-3 w-3 text-accent" />
  </span>
);

export interface Feature {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
  color?: string;
  category?: string;
  href: string;
  dashboardTitle?: string;
}

export const tools: Feature[] = [
  {
    id: 'sales-agent-chat-ai',
    title: 'SalesAgentChat AI',
    description: 'Deploy a super-intelligent AI agent on your website or social media to engage users, answer complex questions with market data, and capture qualified leads 24/7.',
    icon: <AiIcon icon={<MessageCircle />} />,
    color: 'hsl(var(--primary))',
    category: 'Sales & Marketing',
    href: '/solutions/estchat-x3',
    dashboardTitle: 'Sales Chat AI',
  },
  {
    id: 'ai-listing-portal',
    title: 'AI Listing Portal',
    description: 'Create a single source of truth for your property data. Our AI consolidates, verifies, and archives listings to eliminate noise, enforce accuracy, and syndicate perfectly formatted data to all major portals.',
    icon: <AiIcon icon={<FileJson />} />,
    color: 'hsl(var(--accent))',
    category: 'Data Management',
    href: '/solutions/mega-listing-pro-2',
  },
  {
    id: 'pro-search-eng-x3',
    title: 'Pro Search Engine X3',
    description: 'A triple-engine AI search that combines keyword speed, semantic understanding, and predictive analysis to find opportunities others miss.',
    icon: <AiIcon icon={<Telescope />} />,
    color: 'hsl(var(--secondary))',
    category: 'Market Intelligence',
    href: '/solutions/pro-search-eng-x3',
  },
  {
    id: 'ai-marketing-copilot',
    title: 'AI Marketing Copilot',
    description: 'Generate hyper-personalized marketing content, from social media posts to email campaigns, optimized by Gemini AI for maximum engagement.',
    icon: <AiIcon icon={<Megaphone />} />,
    color: 'hsl(210 40% 50%)',
    category: 'Sales & Marketing',
    href: '/me/tool/ai-marketing-copilot',
  },
  {
    id: 'deal-analyzer-ai',
    title: 'Deal Analyzer AI',
    description: 'Leverage Gemini AI to quickly assess investment opportunities, analyze potential returns, and identify risks with unparalleled accuracy.',
    icon: <AiIcon icon={<BarChart3 />} />,
    color: 'hsl(140 40% 50%)',
    category: 'Investment',
    href: '/me/tool/deal-analyzer',
  },
  {
    id: 'ai-document-processor',
    title: 'AI Document Processor',
    description: 'Automate the extraction of key information from contracts, legal documents, and reports using Gemini AI, saving hours of manual work.',
    icon: <AiIcon icon={<ReceiptText />} />,
    color: 'hsl(45 90% 50%)',
    category: 'Operations',
    href: '/me/tool/ai-document-processor',
  },
  {
    id: 'flow-automation-studio',
    title: 'Flow Automation Studio',
    description: 'Visually design and deploy multi-step AI workflows with Gemini to automate repetitive tasks across your entire real estate operation.',
    icon: <AiIcon icon={<Workflow />} />,
    color: 'hsl(300 50% 60%)',
    category: 'Automation',
    href: '/me/flows',
  },
  {
    id: 'market-insights-dashboard',
    title: 'Market Insights Dashboard',
    description: 'Get real-time market trends, predictive analytics, and localized data visualizations powered by Gemini AI for strategic decision-making.',
    icon: <AiIcon icon={<LayoutDashboard />} />,
    color: 'hsl(var(--info))', // Assuming --info is a defined color variable
    category: 'Market Intelligence',
    href: '/me/tool/market-insights',
  },
  {
    id: 'ai-lead-qualifier',
    title: 'AI Lead Qualifier',
    description: 'Automatically qualify leads based on custom criteria and historical data, ensuring your sales team focuses on the most promising opportunities with Gemini AI.',
    icon: <AiIcon icon={<Target />} />,
    color: 'hsl(var(--success))', // Assuming --success is a defined color variable
    category: 'Sales & CRM',
    href: '/me/tool/ai-lead-qualifier',
  },
  {
    id: 'property-valuation-ai',
    title: 'Property Valuation AI',
    description: 'Generate accurate property valuations in real-time using advanced AI models, factoring in market data, comparable sales, and unique property features.',
    icon: <AiIcon icon={<Building />} />,
    color: 'hsl(var(--warning))', // Assuming --warning is a defined color variable
    category: 'Valuation',
    href: '/me/tool/property-valuation-ai',
  },
  {
    id: 'ai-content-generator',
    title: 'AI Content Generator',
    description: 'Effortlessly create engaging property descriptions, blog posts, and marketing copy with Gemini AI, tailored to your brand voice and target audience.',
    icon: <AiIcon icon={<Feather />} />,
    color: 'hsl(var(--tertiary))', // Assuming --tertiary is a defined color variable
    category: 'Content Creation',
    href: '/me/tool/ai-content-generator',
  },
  {
    id: 'developer-backend-sync',
    title: 'Developer Backend Sync',
    description: 'Seamlessly integrate and synchronize data from developer CRMs and ERPs into your Entrestate ecosystem, powered by robust API connectors.',
    icon: <AiIcon icon={<Code />} />,
    color: 'hsl(var(--dark))', // Assuming --dark is a defined color variable
    category: 'Integration',
    href: '/me/tool/developer-backend-sync',
  },
  // Adding more AI-powered tools to reach approximately 40
  {
    id: 'ai-property-matcher',
    title: 'AI Property Matcher',
    description: 'Connect clients with ideal properties using intelligent matching algorithms that consider preferences, budget, and market trends, powered by Gemini AI.',
    icon: <AiIcon icon={<CircleDashed />} />,
    color: 'hsl(240 5% 64%)',
    category: 'Client Management',
    href: '/me/tool/ai-property-matcher',
  },
  {
    id: 'predictive-market-forecaster',
    title: 'Predictive Market Forecaster',
    description: 'Anticipate future market shifts and identify emerging opportunities with advanced predictive analytics from Gemini AI.',
    icon: <AiIcon icon={<Lightbulb />} />,
    color: 'hsl(36 70% 50%)',
    category: 'Market Intelligence',
    href: '/me/tool/predictive-market-forecaster',
  },
  {
    id: 'ai-client-onboarding',
    title: 'AI Client Onboarding',
        description: 'Automate the client onboarding process, from initial contact to document collection, ensuring a smooth and efficient start with Gemini AI.',
    icon: <AiIcon icon={<UserPlus />} />,
    color: 'hsl(180 60% 40%)',
    category: 'Client Management',
    href: '/me/tool/ai-client-onboarding',
  },
  {
    id: 'ai-contract-reviewer',
    title: 'AI Contract Reviewer',
    description: 'Expedite contract review by automatically highlighting key clauses, potential risks, and inconsistencies with Gemini AI.',
    icon: <AiIcon icon={<FileText />} />,
    color: 'hsl(270 50% 50%)',
    category: 'Legal & Compliance',
    href: '/me/tool/ai-contract-reviewer',
  },
  {
    id: 'social-media-optimizer',
    title: 'Social Media Optimizer',
    description: 'Optimize your social media presence with AI-driven content scheduling, audience targeting, and performance analytics.',
    icon: <AiIcon icon={<Megaphone />} />,
    color: 'hsl(330 80% 55%)',
    category: 'Sales & Marketing',
    href: '/me/tool/social-media-optimizer',
  },
  {
    id: 'virtual-staging-ai',
    title: 'Virtual Staging AI',
    description: 'Transform empty spaces into beautifully staged virtual representations with AI, attracting more potential buyers.',
    icon: <AiIcon icon={<LayoutDashboard />} />,
    color: 'hsl(180 20% 40%)',
    category: 'Marketing & Visualization',
    href: '/me/tool/virtual-staging-ai',
  },
  {
    id: 'ai-personal-assistant',
    title: 'AI Personal Assistant',
    description: 'A dedicated AI assistant to manage your schedule, set reminders, and provide quick answers to real estate queries, powered by Gemini.',
    icon: <AiIcon icon={<Bot />} />,
    color: 'hsl(240 60% 50%)',
    category: 'Productivity',
    href: '/me/assistant',
  },
  {
    id: 'market-report-generator',
    title: 'Market Report Generator',
    description: 'Generate comprehensive and visually appealing market reports in minutes, leveraging AI to synthesize vast amounts of data.',
    icon: <AiIcon icon={<BarChart3 />} />,
    color: 'hsl(120 40% 40%)',
    category: 'Market Intelligence',
    href: '/me/tool/market-report-generator',
  },
  {
    id: 'email-campaign-ai',
    title: 'Email Campaign AI',
    description: 'Craft high-converting email campaigns with AI-generated copy, personalized subject lines, and optimal send times.',
    icon: <AiIcon icon={<Mail />} />,
    color: 'hsl(0 60% 50%)',
    category: 'Sales & Marketing',
    href: '/me/tool/email-campaign-ai',
  },
  {
    id: 'data-cleaner-ai',
    title: 'Data Cleaner AI',
    description: 'Automatically identify and rectify inconsistencies, duplicates, and errors in your property and client databases with Gemini AI.',
    icon: <AiIcon icon={<Database />} />,
    color: 'hsl(200 60% 40%)',
    category: 'Data Management',
    href: '/me/tool/data-cleaner-ai',
  },
  {
    id: 'lead-nurturing-ai',
    title: 'Lead Nurturing AI',
    description: 'Develop and automate personalized lead nurturing sequences, ensuring timely follow-ups and relevant content delivery with Gemini AI.',
    icon: <AiIcon icon={<Workflow />} />,
    color: 'hsl(60 70% 50%)',
    category: 'Sales & CRM',
    href: '/me/tool/lead-nurturing-ai',
  },
  {
    id: 'investment-opportunity-finder',
    title: 'Investment Opportunity Finder',
    description: 'Identify lucrative real estate investment opportunities based on your criteria, market data, and predictive AI analytics.',
    icon: <AiIcon icon={<Telescope />} />,
    color: 'hsl(280 50% 60%)',
    category: 'Investment',
    href: '/me/tool/investment-opportunity-finder',
  },
  {
    id: 'client-feedback-analyzer',
    title: 'Client Feedback Analyzer',
    description: 'Process and analyze client feedback from various sources using AI to derive actionable insights for improved services and satisfaction.',
    icon: <AiIcon icon={<MessageCircle />} />,
    color: 'hsl(10 70% 50%)',
    category: 'Client Management',
    href: '/me/tool/client-feedback-analyzer',
  },
  {
    id: 'property-image-enhancer',
    title: 'Property Image Enhancer',
    description: 'Enhance property photos with AI-driven corrections, lighting adjustments, and stylistic improvements for stunning visuals.',
    icon: <AiIcon icon={<Image />} />,
    color: 'hsl(160 40% 50%)',
    category: 'Marketing & Visualization',
    href: '/me/tool/property-image-enhancer',
  },
  {
    id: 'comparable-market-analysis-ai',
    title: 'Comparable Market Analysis AI',
    description: 'Generate precise comparable market analyses (CMA) instantly with AI, helping you price properties competitively.',
    icon: <AiIcon icon={<BarChart3 />} />,
    color: 'hsl(200 80% 40%)',
    category: 'Valuation',
    href: '/me/tool/comparable-market-analysis-ai',
  },
  {
    id: 'ai-powered-faq',
    title: 'AI-Powered FAQ',
    description: 'Deploy an intelligent FAQ system on your website or internal portal that uses Gemini AI to answer common questions instantly.',
    icon: <AiIcon icon={<HelpCircle />} />,
    color: 'hsl(50 90% 60%)',
    category: 'Customer Support',
    href: '/me/tool/ai-powered-faq',
  },
  {
    id: 'virtual-tour-creator',
    title: 'Virtual Tour Creator',
    description: 'Generate immersive virtual property tours from images and floor plans with AI, enhancing online listings.',
    icon: <AiIcon icon={<Rocket />} />,
    color: 'hsl(320 60% 50%)',
    category: 'Marketing & Visualization',
    href: '/me/tool/virtual-tour-creator',
  },
  {
    id: 'ai-legal-assistant',
    title: 'AI Legal Assistant',
    description: 'Get AI-driven insights and support for legal documents, compliance checks, and regulatory queries in real estate.',
    icon: <AiIcon icon={<Gavel />} />,
    color: 'hsl(200 20% 30%)',
    category: 'Legal & Compliance',
    href: '/me/tool/ai-legal-assistant',
  },
  {
    id: 'client-segmentation-ai',
    title: 'Client Segmentation AI',
    description: 'Segment your client base effectively with AI, identifying high-value clients and tailoring engagement strategies.',
    icon: <AiIcon icon={<Users2 />} />,
    color: 'hsl(100 40% 50%)',
    category: 'Client Management',
    href: '/me/tool/client-segmentation-ai',
  },
  {
    id: 'property-maintenance-ai',
    title: 'Property Maintenance AI',
    description: 'Predict maintenance needs, optimize scheduling, and manage vendors with AI for efficient property management.',
    icon: <AiIcon icon={<Settings />} />,
    color: 'hsl(250 30% 40%)',
    category: 'Property Management',
    href: '/me/tool/property-maintenance-ai',
  },
  {
    id: 'market-analysis-reports-ai',
    title: 'Market Analysis Reports AI',
    description: 'Generate in-depth market analysis reports, including competitive landscapes and growth projections, with Gemini AI.',
    icon: <AiIcon icon={<BarChart3 />} />,
    color: 'hsl(190 70% 50%)',
    category: 'Market Intelligence',
    href: '/me/tool/market-analysis-reports-ai',
  },
  {
    id: 'ai-driven-investor-matching',
    title: 'AI-Driven Investor Matching',
    description: 'Match properties with potential investors based on AI-analyzed preferences, risk profiles, and investment goals.',
    icon: <AiIcon icon={<Lightbulb />} />,
    color: 'hsl(310 60% 50%)',
    category: 'Investment',
    href: '/me/tool/ai-driven-investor-matching',
  },
  {
    id: 'automated-lease-generation',
    title: 'Automated Lease Generation',
    description: 'Generate customized lease agreements and contracts automatically, ensuring legal compliance and accuracy with AI.',
    icon: <AiIcon icon={<FileText />} />,
    color: 'hsl(15 80% 60%)',
    category: 'Operations',
    href: '/me/tool/automated-lease-generation',
  },
  {
    id: 'ai-powered-property-search',
    title: 'AI-Powered Property Search',
    description: 'Enhance property search with AI, allowing natural language queries and intelligent recommendations.',
    icon: <AiIcon icon={<Search />} />,
    color: 'hsl(70 50% 60%)',
    category: 'Market Intelligence',
    href: '/me/tool/ai-powered-property-search',
  },
  {
    id: 'crm-integration-ai',
    title: 'CRM Integration AI',
    description: 'Seamlessly integrate your CRM with AI, automating data entry, lead scoring, and client communication logs.',
    icon: <AiIcon icon={<Code />} />,
    color: 'hsl(220 40% 50%)',
    category: 'Sales & CRM',
    href: '/me/tool/crm-integration-ai',
  },
  {
    id: 'ai-email-responder',
    title: 'AI Email Responder',
    description: 'Automate responses to common email inquiries, draft personalized replies, and manage your inbox efficiently with Gemini AI.',
    icon: <AiIcon icon={<Mail />} />,
    color: 'hsl(180 80% 40%)',
    category: 'Productivity',
    href: '/me/tool/ai-email-responder',
  },
  {
    id: 'transaction-predictor-ai',
    title: 'Transaction Predictor AI',
    description: 'Predict the likelihood of successful transactions based on historical data and real-time market signals with Gemini AI.',
    icon: <AiIcon icon={<TrendingUp />} />,
    color: 'hsl(30 90% 50%)',
    category: 'Investment',
    href: '/me/tool/transaction-predictor-ai',
  },
  {
    id: 'ai-powered-chatbots',
    title: 'AI-Powered Chatbots',
    description: 'Create and deploy intelligent chatbots for customer service, lead generation, and property inquiries, powered by Gemini AI.',
    icon: <AiIcon icon={<Bot />} />,
    color: 'hsl(270 70% 60%)',
    category: 'Customer Support',
    href: '/me/tool/ai-powered-chatbots',
  },
  {
    id: 'construction-project-ai',
    title: 'Construction Project AI',
    description: 'Manage construction projects efficiently with AI, predicting timelines, optimizing resource allocation, and identifying potential delays.',
    icon: <AiIcon icon={<HardHat />} />,
    color: 'hsl(40 80% 50%)',
    category: 'Property Management',
    href: '/me/tool/construction-project-ai',
  },
  {
    id: 'ai-powered-analytics',
    title: 'AI-Powered Analytics',
    description: 'Gain deep insights into your business performance with AI-driven analytics, identifying trends and recommending strategic adjustments.',
    icon: <AiIcon icon={<LineChart />} />,
    color: 'hsl(100 70% 40%)',
    category: 'Business Intelligence',
    href: '/me/tool/ai-powered-analytics',
  },
  {
    id: 'property-virtual-tours',
    title: 'Property Virtual Tours',
    description: 'Generate interactive 3D virtual tours of properties from existing floor plans and images, enhancing online viewing experiences.',
    icon: <AiIcon icon={<Camera />} />,
    color: 'hsl(290 50% 50%)',
    category: 'Marketing & Visualization',
    href: '/me/tool/property-virtual-tours',
  },
  {
    id: 'ai-driven-contract-drafting',
    title: 'AI-Driven Contract Drafting',
    description: 'Automate the drafting of complex real estate contracts and agreements, ensuring legal accuracy and compliance with Gemini AI.',
    icon: <AiIcon icon={<FileText />} />,
    color: 'hsl(20 90% 60%)',
    category: 'Legal & Compliance',
    href: '/me/tool/ai-driven-contract-drafting',
  },
  {
    id: 'ai-powered-due-diligence',
    title: 'AI-Powered Due Diligence',
    description: 'Streamline due diligence processes with AI, quickly analyzing vast amounts of data to identify risks and opportunities.',
    icon: <AiIcon icon={<SearchCheck />} />,
    color: 'hsl(260 50% 50%)',
    category: 'Operations',
    href: '/me/tool/ai-powered-due-diligence',
  },
  {
    id: 'ai-for-property-showings',
    title: 'AI for Property Showings',
    description: 'Optimize property showing schedules, gather feedback, and analyze client reactions with AI to improve conversion rates.',
    icon: <AiIcon icon={<CalendarCheck />} />,
    color: 'hsl(170 60% 40%)',
    category: 'Sales & CRM',
    href: '/me/tool/ai-for-property-showings',
  },
  {
    id: 'ai-powered-risk-assessment',
    title: 'AI-Powered Risk Assessment',
    description: 'Identify and mitigate risks associated with property investments, market volatility, and client portfolios using Gemini AI.',
    icon: <AiIcon icon={<ShieldAlert />} />,
    color: 'hsl(340 70% 50%)',
    category: 'Investment',
    href: '/me/tool/ai-powered-risk-assessment',
  },
  {
    id: 'automated-document-classification',
    title: 'Automated Document Classification',
    description: 'Automatically categorize and organize large volumes of real estate documents, improving searchability and compliance with Gemini AI.',
    icon: <AiIcon icon={<FolderOpen />} />,
    color: 'hsl(80 50% 60%)',
    category: 'Data Management',
    href: '/me/tool/automated-document-classification',
  },
  {
    id: 'ai-enhanced-client-communication',
    title: 'AI-Enhanced Client Communication',
    description: 'Improve client communication with AI-suggested responses, personalized messaging, and sentiment analysis for better engagement.',
    icon: <AiIcon icon={<MessageSquareMore />} />,
        color: 'hsl(200 70% 50%)',
    category: 'Client Management',
    href: '/me/tool/ai-enhanced-client-communication',
  },
  {
    id: 'ai-for-property-management',
    title: 'AI for Property Management',
    description: 'Streamline property management tasks, including tenant screening, rent collection, and maintenance requests, with intelligent automation.',
    icon: <AiIcon icon={<Building2 />} />,
    color: 'hsl(240 40% 30%)',
    category: 'Property Management',
    href: '/me/tool/ai-for-property-management',
  },
  {
    id: 'ai-driven-marketing-analytics',
    title: 'AI-Driven Marketing Analytics',
    description: 'Measure and optimize your marketing campaigns with AI-powered analytics, identifying effective strategies and areas for improvement.',
    icon: <AiIcon icon={<BarChartBig />} />,
    color: 'hsl(10 90% 50%)',
    category: 'Sales & Marketing',
    href: '/me/tool/ai-driven-marketing-analytics',
  },
  {
    id: 'ai-powered-recruitment',
    title: 'AI-Powered Recruitment',
    description: 'Utilize AI to identify top talent in the real estate industry, streamline the hiring process, and build high-performing teams.',
    icon: <AiIcon icon={<UserPlus />} />,
    color: 'hsl(300 70% 50%)',
    category: 'Human Resources',
    href: '/me/tool/ai-powered-recruitment',
  },
  {
    id: 'ai-for-real-estate-investors',
    title: 'AI for Real Estate Investors',
    description: 'Comprehensive AI tools for real estate investors, providing market analysis, deal scouting, and portfolio optimization.',
    icon: <AiIcon icon={<PiggyBank />} />,
    color: 'hsl(60 80% 40%)',
    category: 'Investment',
    href: '/me/tool/ai-for-real-estate-investors',
  },
  {
    id: 'ai-powered-virtual-assistant',
    title: 'AI-Powered Virtual Assistant',
    description: 'A sophisticated virtual assistant for daily tasks, data retrieval, and proactive support across your Entrestate workspace, powered by Gemini AI.',
    icon: <AiIcon icon={<BotMessageSquare />} />,
    color: 'hsl(220 70% 60%)',
    category: 'Productivity',
    href: '/me/assistant',
  },
  {
    id: 'ai-for-commercial-real-estate',
    title: 'AI for Commercial Real Estate',
    description: 'Specialized AI tools for commercial real estate professionals, offering insights into market trends, property valuation, and investment analysis.',
    icon: <AiIcon icon={<Building />} />,
    color: 'hsl(180 30% 20%)',
    category: 'Commercial Real Estate',
    href: '/me/tool/ai-for-commercial-real-estate',
  },
  {
    id: 'ai-powered-crm-enhancer',
    title: 'AI-Powered CRM Enhancer',
    description: 'Supercharge your CRM with AI, adding predictive lead scoring, automated client profiling, and intelligent task recommendations.',
    icon: <AiIcon icon={<BrainCircuit />} />,
    color: 'hsl(350 70% 50%)',
    category: 'Sales & CRM',
    href: '/me/tool/ai-powered-crm-enhancer',
  },
  {
    id: 'ai-driven-market-forecasting',
    title: 'AI-Driven Market Forecasting',
    description: 'Accurate long-term and short-term market forecasts using advanced AI models and vast datasets, helping you stay ahead of trends.',
    icon: <AiIcon icon={<TrendingUp />} />,
    color: 'hsl(90 60% 40%)',
    category: 'Market Intelligence',
    href: '/me/tool/ai-driven-market-forecasting',
  },
  {
    id: 'ai-for-property-development',
    title: 'AI for Property Development',
    description: 'Optimize property development projects from land acquisition to sales, with AI-powered feasibility studies, cost analysis, and risk management.',
    icon: <AiIcon icon={<Construction />} />,
    color: 'hsl(25 80% 50%)',
    category: 'Property Development',
    href: '/me/tool/ai-for-property-development',
  },
  {
    id: 'ai-powered-virtual-broker',
    title: 'AI-Powered Virtual Broker',
    description: 'A virtual AI broker capable of handling client inquiries, conducting property tours, and assisting with negotiations, available 24/7.',
    icon: <AiIcon icon={<BriefcaseBusiness />} />,
    color: 'hsl(240 50% 50%)',
    category: 'Sales & Client Management',
    href: '/me/tool/ai-powered-virtual-broker',
  },
];
