import type { Project } from '@/src/lib/market/types';
import { loadProjects } from '@/src/lib/market/load';

export async function findProjectByName(nameOrId: string): Promise<Project|null> {
  const all = await loadProjects(2000);
  const needle = nameOrId.toLowerCase().trim();
  const exact = all.find(p => p.id.toLowerCase() === needle || (p.name||'').toLowerCase() === needle);
  if (exact) return exact as any;
  const fuzzy = all.find(p => (p.name||'').toLowerCase().includes(needle));
  return fuzzy ? (fuzzy as any) : null;
}

export function compareKpis(a: Project, b: Project) {
  const rows = [
    ['Developer', a.developer||'—', b.developer||'—'],
    ['City', a.city||'—', b.city||'—'],
    ['Area', a.area||'—', b.area||'—'],
    ['Price From (AED)', fmt(a.priceFrom), fmt(b.priceFrom)],
    ['Bedrooms', (a.bedrooms||[]).join(', ')||'—', (b.bedrooms||[]).join(', ')||'—'],
    ['Launch', a.launchYear||'—', b.launchYear||'—'],
    ['Completion', a.completionYear||'—', b.completionYear||'—'],
  ];
  return rows;
}

function fmt(n?: number|null){ return n? n.toLocaleString('en-AE') : '—'; }

export function renderCompareHtml(title: string, aName: string, bName: string, rows: string[][]){
  const tr = rows.map(r => `<tr><th style="text-align:left;padding:8px;background:#f6f6f6;">${r[0]}</th><td style="padding:8px;">${r[1]}</td><td style="padding:8px;">${r[2]}</td></tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title></head>
  <body style="font-family:ui-sans-serif,system-ui,Segoe UI,Roboto,Helvetica,Arial;padding:24px;">
    <h1 style="margin:0 0 12px 0;">${title}</h1>
    <h3 style="margin:0 0 24px 0;">${aName} vs ${bName}</h3>
    <table style="border-collapse:collapse;width:100%;border:1px solid #eaeaea;">
      <thead><tr><th></th><th>${aName}</th><th>${bName}</th></tr></thead>
      <tbody>${tr}</tbody>
    </table>
    <p style="margin-top:24px;font-size:12px;color:#666;">Generated by Entrestate • ${new Date().toLocaleString('en-AE')}</p>
  </body></html>`;
}
