
'use client';

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { UserPlus, Workflow, Lightbulb } from "lucide-react";

// This data would be dynamically generated by an AI flow in a real application
const recommendations = {
    users: [
        { name: "Jane Smith", title: "Top Agent @ Emaar", image: "https://i.pravatar.cc/150?u=d" },
        { name: "Alex Johnson", title: "Off-plan Specialist", image: "https://i.pravatar.cc/150?u=e" },
    ],
    flows: [
        { name: "Automated Lead Nurturing", description: "A flow to automatically follow up with new leads via WhatsApp and email." },
    ]
};

export function RecommendedForYou() {
    return (
        <Card className="sticky top-24">
            <CardHeader>
                <CardTitle>Recommended for You</CardTitle>
                <CardDescription>Intelligent suggestions from your AI co-pilot.</CardDescription>
            </CardHeader>
            <CardContent>
                <div className="space-y-4">
                    <div>
                        <h4 className="text-sm font-semibold mb-2 flex items-center gap-2">
                            <UserPlus className="h-4 w-4" />
                            People to Connect With
                        </h4>
                        <div className="space-y-2">
                            {recommendations.users.map(user => (
                                <div key={user.name} className="flex items-center justify-between">
                                    <div className="flex items-center gap-2">
                                        <Avatar className="h-8 w-8">
                                            <AvatarImage src={user.image} />
                                            <AvatarFallback>{user.name.charAt(0)}</AvatarFallback>
                                        </Avatar>
                                        <div>
                                            <p className="text-sm font-semibold">{user.name}</p>
                                            <p className="text-xs text-muted-foreground">{user.title}</p>
                                        </div>
                                    </div>
                                    <Button size="sm" variant="outline">Connect</Button>
                                </div>
                            ))}
                        </div>
                    </div>
                     <div>
                        <h4 className="text-sm font-semibold mb-2 flex items-center gap-2">
                            <Workflow className="h-4 w-4" />
                            Flows to Try
                        </h4>
                        <div>
                            <p className="text-sm font-semibold">{recommendations.flows[0].name}</p>
                            <p className="text-xs text-muted-foreground">{recommendations.flows[0].description}</p>
                             <Button size="sm" variant="outline" className="mt-1">View Flow</Button>
                        </div>
                    </div>
                </div>
            </CardContent>
        </Card>
    );
}
