
'use client';

import { PageHeader } from "@/components/ui/page-header";
import { GeminiLeadInsightCard } from "@/components/lead-intelligence/gemini-lead-insight-card";
import { LeadPrioritization } from "@/components/lead-intelligence/lead-prioritization";
import { Button } from "@/components/ui/button";

export default function LeadIntelligencePage() {
  // This data would be dynamically generated by an AI flow in a real application
  const insight = "John Doe has viewed the Emaar Beachfront brochure 3 times. He seems highly engaged.";
  const actionText = "Launch a personalized follow-up sequence";
  const actionLink = "/me/lead-intelligence/123/sequence"; // Placeholder

  return (
    <div className="p-4 md:p-8">
      <PageHeader
        title="Lead Intelligence"
        description="Your AI Co-pilot for converting leads into deals."
        actions={<Button>Add New Lead</Button>}
      />
      <div className="grid gap-6 mt-4 md:grid-cols-3">
        <GeminiLeadInsightCard 
          insight={insight}
          actionLink={actionLink}
          actionText={actionText}
        />
        <LeadPrioritization />
      </div>
    </div>
  );
}
