
'use client';

import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { GeminiListingInsightCard } from "@/components/listing-portal/gemini-listing-insight-card";
import { ListingOptimizer } from "@/components/listing-portal/listing-optimizer";
import { UnifiedMarketRegistry } from "@/components/listing-portal/unified-market-registry";

export default function ListingIntelligencePage() {
  // This data would be dynamically generated by an AI flow in a real application
  const insight = "Your listing for the 'Luxury Villa in Palm Jumeirah' is underperforming. Its photos have a low quality score.";
  const actionText = "Automatically enhance photos with AI";
  const actionLink = "/me/listing-portal/PF-123/enhance"; // Placeholder

  return (
    <div className="p-4 md:p-8">
      <PageHeader
        title="Listing Intelligence"
        description="Your AI Co-pilot for optimizing your property listings."
        actions={
            <Link href="/me/listing-portal/create-listing">
                <Button>Create New Listing</Button>
            </Link>
        }
      />
      <div className="grid gap-6 mt-4 md:grid-cols-3">
        <GeminiListingInsightCard 
          insight={insight}
          actionLink={actionLink}
          actionText={actionText}
        />
        <ListingOptimizer />
      </div>
      <div className="mt-6">
        <h3 className="text-2xl font-bold mb-4">Unified Market Registry</h3>
        <UnifiedMarketRegistry />
      </div>
    </div>
  );
}
