name: build-and-e2e

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build
        env:
          NEXT_PUBLIC_APP_URL: "http://127.0.0.1:3000"
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: "dummy"
          PAYPAL_CLIENT_SECRET: "dummy"
          FIREBASE_PROJECT_ID: "dummy"
          GENKIT_DISABLE_TELEMETRY: "1"
        run: npm run build

      - name: Start server
        env:
          NEXT_PUBLIC_APP_URL: "http://127.0.0.1:3000"
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: "dummy"
          PAYPAL_CLIENT_SECRET: "dummy"
          FIREBASE_PROJECT_ID: "dummy"
          GENKIT_DISABLE_TELEMETRY: "1"
        run: |
          npm start &
          npx wait-on http://127.0.0.1:3000

      - name: Run e2e tests
        env:
          BASE_URL: "http://127.0.0.1:3000"
        run: npm run e2e
